[preview]
max_width   = 3000
max_height  = 3000
image_delay = 30

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo"},
    { mime = "application/x-subrip", run = "mediainfo"},
    { name = "*.md", run = "glow" },
]
